language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
cache: yarn
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
