language: node_js
node_js:
  - "7"
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test:all
  - yarn doc
  - yarn build
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
  - povider: pages
    github_token: $GITHUB_TOKEN
    local_dir: docs
    skip_cleanup: true
    on:
      tags: true
